# The default config file is designed for a simple setup.
# For more complex setups check the github examples.

reload-message:

global-settings:
  first-join:
    enabled: true # You CAN remove this altogether, by doing so it will default to TRUE
    to-player:
      # What sound effects should be played to the player when they first join?
      # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      sound-effect:
        sound: UI_TOAST_CHALLENGE_COMPLETE
        settings:
          volume: 1
          pitch: 1
      # What Effects should be given to the player when they join for the first time?
      # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
      effects:
        1:
          # Will apply Strength 4, for 100 seconds to the player.
          effect: INCREASE_DAMAGE
          duration: 100
          level: 4 # FULL NUMBER ONLY
        2:
          effect: FAST_DIGGING
          duration: 100
          level: 10 # FULL NUMBER ONLY
      commands:
        - "/say hello %player_name%"
        - "/my custom epic command here"
      # Settings for a Custom Title Message
      title-message:
        title: "MY EPIC TITLE"
        sub-title: "MY EPIC SUB TITLE"
        settings:
          fade-in: 1
          stay: 7
          fade-out: 2
          duration: 5
      # Settings for a Custom Boss Bar
      boss-bar:
        title: "MY EPIC TITLE"
        color: BLUE
        style: SOLID
        flags:
          - CREATE_FOG
        duration: 5
      # Settings for a Custom Message
      message:
        - "line 1"
        - "line 2"
      # Settings for a Custom Action Bar
      action-bar:
        message: "This will appear above the player's hot bar"
        duration: 5

    # Settings for messages shown to all online players (EXCLUDING THE PLAYER THAT JOINED)
    to-everyone-online:
      # What sound effects should be played to every player online when someone
      # joins for the first time? (EXCLUDING THE PLAYER THAT JOINED)
      # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
      sound-effect:
        sound: UI_TOAST_CHALLENGE_COMPLETE
        settings:
          volume: 1
          pitch: 1
      # What effects should be played to every player online when someone
      # joins for the first time? (EXCLUDING THE PLAYER THAT JOINED)
      # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
      effects:
        1:
          # Will apply Strength 4, for 100 seconds to the player.
          effect: INCREASE_DAMAGE
          duration: 100
          level: 4 # FULL NUMBER ONLY
        2:
          effect: FAST_DIGGING
          duration: 100
          level: 10 # FULL NUMBER ONLY
      # Commands will be run for every player, so I really would NOT recommend using any
      # broadcast command here!
      commands:
        - "/say hello %player_name% joined "
        - "/my custom epic command here"
      # Settings for a Custom Title Message
      title-message:
        title: "%player_name% joined for the first time!"
        sub-title: "give them a fat hello!"
        settings:
          fade-in: 1
          stay: 7
          fade-out: 2
      # Settings for a Custom Boss Bar
      boss-bar:
        title: "%player_name% joined for the first time!"
        color: BLUE
        style: SOLID
        flags:
          - CREATE_FOG
        duration: 5
      # Settings for a Custom Message
      message:
        - "%player_name% joined for the first time!"
        - "line 2"
      # Settings for a Custom Action Bar
      action-bar:
        message: "This will appear above the player's hot bar"
        duration: 5